02:39:15 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
02:39:38 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
02:55:35 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:06:01 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:09:23 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:09:23 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
03:10:02 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:10:02 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
03:12:58 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:12:58 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
03:13:13 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:13:13 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
03:15:02 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:15:02 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
03:51:12 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03:51:12 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08:53:31 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08:54:25 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:54:25 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08:54:58 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08:55:53 PM:DEBUG [logger_base.py:14] Mensaje a nivel debug
08:55:53 PM:INFO [logger_base.py:15] Mensaje a nivel info
08:55:53 PM:WARNING [logger_base.py:16] Mensaje a nivel warning
08:55:53 PM:ERROR [logger_base.py:17] Mensaje a nivel error
08:55:53 PM:CRITICAL [logger_base.py:18] Mensaje a nivel critical
08:56:07 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08:56:40 PM:INFO [menu_app_usuario.py:42] Has de la aplicación, ¡Hasta luego!
09:11:58 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
09:11:58 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
09:12:22 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
09:12:43 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08:01:11 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:01:11 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001F8BBA3B890>
08:01:11 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:43] Usuario a eliminar: Usuario: 3 None None
08:01:11 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:01:11 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
08:01:11 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:53] Usuario eliminado: 0
08:01:11 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:01:11 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:35] Usuario a actualizar: Usuario: 1  654
08:01:11 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:01:11 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
08:01:11 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:58] Usuario modificado: 1
08:01:11 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:01:11 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None Tincho 321
08:01:11 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:01:11 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
08:01:11 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:63] Usuario insertado: 1
08:01:11 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:01:11 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
08:01:11 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:01:11 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
08:01:11 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001F8BD971BE0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:01:11 PM:DEBUG [usuario_dao.py:68] Usuario: 1  654
08:01:11 PM:DEBUG [usuario_dao.py:68] Usuario: 2 jgarcia 789
08:01:11 PM:DEBUG [usuario_dao.py:68] Usuario: 4 Tincho 321
