08:34:00 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000013246A1F8C0>
08:34:00 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000013246A8DAD0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
06:58:32 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
06:58:32 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
06:59:59 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
07:00:58 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
07:01:10 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:01:10 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
07:04:16 PM:ERROR [conexion.py:42] Ocurrió un error al obtener el pool: connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied

07:19:39 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000202A8AABF50>
07:19:39 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000202AAA69AD0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:28 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:20:28 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000236DBB3B4D0>
07:20:28 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:28 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:20:28 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:20:28 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:20:28 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:28 PM:INFO [menu_app_usuario.py:18] Usuario: 1 mgonzalez 456
07:20:28 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:20:35 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:20:35 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:35 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:20:35 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:20:35 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:20:35 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:35 PM:INFO [menu_app_usuario.py:18] Usuario: 1 mgonzalez 456
07:20:35 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:20:43 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:20:43 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:43 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None Pedro 123
07:20:43 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:20:43 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:20:43 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:43 PM:INFO [menu_app_usuario.py:25] Usuario insertado: 1
07:20:45 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:20:45 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:45 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:20:45 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:20:45 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:20:45 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:45 PM:INFO [menu_app_usuario.py:18] Usuario: 1 mgonzalez 456
07:20:45 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:20:45 PM:INFO [menu_app_usuario.py:18] Usuario: 3 Pedro 123
07:21:36 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:21:36 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:21:36 PM:DEBUG [usuario_dao.py:35] Usuario a actualizar: Usuario: 1 mgonzalez 789
07:21:36 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:21:36 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:21:36 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:21:36 PM:INFO [menu_app_usuario.py:33] Usuario actualizado: 1
07:21:39 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:21:39 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:21:39 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:21:39 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:21:39 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:21:39 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:21:39 PM:INFO [menu_app_usuario.py:18] Usuario: 1 mgonzalez 789
07:21:39 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:21:39 PM:INFO [menu_app_usuario.py:18] Usuario: 3 Pedro 123
07:21:58 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:21:58 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:21:58 PM:DEBUG [usuario_dao.py:35] Usuario a actualizar: Usuario: 1 AndresJuarez 4434
07:21:58 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:21:58 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:21:58 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:21:58 PM:INFO [menu_app_usuario.py:33] Usuario actualizado: 1
07:22:00 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:22:00 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:22:00 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:22:00 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:22:00 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:22:00 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:22:00 PM:INFO [menu_app_usuario.py:18] Usuario: 1 AndresJuarez 4434
07:22:00 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:22:00 PM:INFO [menu_app_usuario.py:18] Usuario: 3 Pedro 123
07:22:15 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:22:15 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:22:15 PM:DEBUG [usuario_dao.py:43] Usuario a eliminar: Usuario: 3 None None
07:22:15 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:22:15 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: 'int' object does not support indexing
07:22:15 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000236DD749CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:23:23 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:23:23 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002642E68B4D0>
07:23:23 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000026430249CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:23:23 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:23:23 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:23:23 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:23:23 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000026430249CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:23:23 PM:INFO [menu_app_usuario.py:18] Usuario: 1 AndresJuarez 4434
07:23:23 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:23:23 PM:INFO [menu_app_usuario.py:18] Usuario: 3 Pedro 123
07:33:33 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:33:33 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000197C232B4D0>
07:33:33 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000197C3F21CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:33:33 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:33:33 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:33:33 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:33:33 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000197C3F21CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:33:33 PM:INFO [menu_app_usuario.py:18] Usuario: 1 AndresJuarez 4434
07:33:33 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:33:33 PM:INFO [menu_app_usuario.py:18] Usuario: 3 Pedro 123
07:33:55 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:33:55 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000197C3F21CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:33:55 PM:DEBUG [usuario_dao.py:43] Usuario a eliminar: Usuario: 3 None None
07:33:55 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:33:55 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:33:55 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000197C3F21CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:33:55 PM:INFO [menu_app_usuario.py:39] Usuario eliminado satisfactoriamente: 1
07:34:03 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:34:03 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000197C3F21CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:34:03 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:34:03 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:34:03 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
07:34:03 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000197C3F21CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:34:03 PM:INFO [menu_app_usuario.py:18] Usuario: 1 AndresJuarez 4434
07:34:03 PM:INFO [menu_app_usuario.py:18] Usuario: 2 jgarcia 789
07:34:40 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
07:46:30 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002604D006A50>
07:46:30 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002604EFE4040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:46:57 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:46:57 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000219BE6C3CB0>
07:46:57 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000219BE221140; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:46:57 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:46:57 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:46:57 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

07:46:57 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000219BE221140; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:47:23 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:47:23 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001936C02FCB0>
07:47:23 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001936BDB0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:47:23 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None GabrielA 123
07:47:23 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:47:23 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: INSERT INTO usuario(username, password) VALUES ('GabrielA', ...
                    ^

07:47:23 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001936BDB0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:56:12 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000215C38F6A50>
07:56:12 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000215C58B8040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:56:57 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:56:57 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001D275F3FCB0>
07:56:57 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001D275CC0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:56:57 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
07:56:57 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:56:57 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

07:56:57 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001D275CC0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:57:30 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
07:57:30 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001DD7CE7FCB0>
07:57:30 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001DD7CC00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:57:30 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None lopezA 123
07:57:30 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
07:57:30 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: INSERT INTO usuario(username, password) VALUES ('lopezA', '1...
                    ^

07:57:30 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001DD7CC00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:00:37 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:00:38 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000026764DCFCB0>
08:00:38 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000026764950370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:00:38 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
08:00:38 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:00:38 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

08:00:38 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000026764950370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:03:07 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:03:08 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000012358D5FCB0>
08:03:08 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000012358AE0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:03:08 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
08:03:08 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:03:08 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

08:03:08 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000012358AE0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:03:18 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:03:18 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000020925B3FCB0>
08:03:18 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000209258C0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:03:18 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None ArturoA 123
08:03:18 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:03:18 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: INSERT INTO usuario(username, password) VALUES ('ArturoA', '...
                    ^

08:03:18 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000209258C0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:09:40 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:09:40 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001F494EDFCB0>
08:09:40 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001F494C60370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:09:40 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
08:09:40 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:09:40 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la columna «id_usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                                       ^

08:09:40 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001F494C60370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:14:51 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:14:51 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002007F87FCB0>
08:14:51 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002007F600370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:14:51 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
08:14:51 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:14:51 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

08:14:51 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002007F600370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:17:20 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:17:20 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000028DF225FCB0>
08:17:20 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000028DF1FE0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:17:20 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None maxiA 123
08:17:20 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:17:20 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: el valor nulo en la columna «id_usuario» de la relación «usuario» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (null, maxiA, 123).

08:17:20 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000028DF1FE0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:18:11 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:18:11 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000013B3F8CFCB0>
08:18:11 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000013B3F650370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:18:11 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None maxiA 123
08:18:11 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:18:11 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: el valor nulo en la columna «id_usuario» de la relación «usuario» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (null, maxiA, 123).

08:18:11 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000013B3F650370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:20:40 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000260A0966A50>
08:20:40 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000260A2938040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:22:26 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
08:22:26 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000016B2E3EFCB0>
08:22:26 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000016B2E170370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
08:22:26 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None RobertoL 123
08:22:26 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
08:22:26 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: el valor nulo en la columna «id_usuario» de la relación «usuario» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (null, RobertoL, 123).

08:22:26 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000016B2E170370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:09:28 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000028C1C406A50>
11:09:28 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000028C1E398480; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:09:54 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:09:54 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001E70B3D3E00>
11:09:54 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001E70B194370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:09:54 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:09:54 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:09:54 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

11:09:54 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001E70B194370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:14:49 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:14:49 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002B3332A3E00>
11:14:49 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002B333064370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:14:49 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:14:49 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:14:49 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

11:14:49 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002B333064370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:21:25 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:21:25 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000018D908F3E00>
11:21:25 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000018D906B4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:21:25 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:21:25 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:21:25 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: SELECT * FROM usuario ORDER BY id_usuario
                      ^

11:21:25 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000018D906B4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:21:40 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:21:40 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000014E38A28050>
11:21:40 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000014E36BA4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:21:40 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None RobertL 123
11:21:40 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:21:40 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la relación «usuario»
LINE 1: INSERT INTO usuario(username, password) VALUES ('RobertL', '...
                    ^

11:21:40 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000014E36BA4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:38:10 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001ADE5346A50>
11:38:10 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001ADE7378040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:38:28 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:38:28 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001C2C299FCB0>
11:38:28 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001C2C2720370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:38:28 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:38:28 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:38:28 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
11:38:28 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001C2C2720370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:38:28 PM:INFO [menu_app_usuario.py:18] Usuario: 1 Jperez 123
11:38:28 PM:INFO [menu_app_usuario.py:18] Usuario: 2 KGomez 567
11:38:43 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:38:43 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001C2C2720370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:38:43 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None raulR 123
11:38:43 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:38:43 PM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: el valor nulo en la columna «id_usuario» de la relación «usuario» viola la restricción de no nulo
DETAIL:  La fila que falla contiene (null, raulR, 123).

11:38:43 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001C2C2720370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:42:27 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:42:27 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000123E7FDFCB0>
11:42:27 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000123E7D60370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:42:27 PM:DEBUG [usuario_dao.py:35] Usuario a actualizar: Usuario: 1 RobertL 1234
11:42:27 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:42:27 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
11:42:27 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000123E7D60370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:42:27 PM:INFO [menu_app_usuario.py:33] Usuario actualizado: 1
11:42:30 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:42:30 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000123E7D60370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:42:30 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:42:30 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:42:30 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
11:42:30 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x00000123E7D60370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:42:30 PM:INFO [menu_app_usuario.py:18] Usuario: 1 RobertL 1234
11:42:30 PM:INFO [menu_app_usuario.py:18] Usuario: 2 KGomez 567
11:43:21 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
11:53:35 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:53:35 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000026DD128FCB0>
11:53:35 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000026DD1010370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:53:35 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:53:35 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:53:35 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
11:53:35 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000026DD1010370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:53:49 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:53:49 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000026DD1010370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:53:49 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:53:49 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:53:49 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
11:53:49 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000026DD1010370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:53:58 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
11:54:05 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000200A5D06A50>
11:54:05 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x00000200A7CB8040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:54:12 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
11:54:12 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001CE89E1FCB0>
11:54:12 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001CE89BA0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:54:12 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
11:54:12 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
11:54:12 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
11:54:12 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001CE89BA0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:04:24 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:04:24 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001CE89BA0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:04:24 AM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
12:04:24 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:04:24 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:04:24 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001CE89BA0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:04:24 AM:INFO [menu_app_usuario.py:18] Usuario: 1 LopezR 123
12:04:24 AM:INFO [menu_app_usuario.py:18] Usuario: 2 DiegoP 456
12:04:43 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:04:43 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001CE89BA0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:04:43 AM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None SolP 322
12:04:43 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:04:43 AM:DEBUG [cursor_del_pool.py:20] Ocurrió una excepción: no existe la columna «username» en la relación «usuario»
LINE 1: INSERT INTO usuario(username, password) VALUES ('SolP', '322...
                            ^

12:04:43 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001CE89BA0370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:02 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:06:02 AM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001EB68E7FCB0>
12:06:02 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:02 AM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
12:06:02 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:06:02 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:06:02 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:02 AM:INFO [menu_app_usuario.py:18] Usuario: 1 LopezR 123
12:06:02 AM:INFO [menu_app_usuario.py:18] Usuario: 2 DiegoP 456
12:06:10 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:06:10 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:10 AM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None SolP 455
12:06:10 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:06:10 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:06:10 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:10 AM:INFO [menu_app_usuario.py:25] Usuario insertado: 1
12:06:15 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:06:15 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:15 AM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
12:06:15 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:06:15 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:06:15 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:15 AM:INFO [menu_app_usuario.py:18] Usuario: 1 LopezR 123
12:06:15 AM:INFO [menu_app_usuario.py:18] Usuario: 2 DiegoP 456
12:06:15 AM:INFO [menu_app_usuario.py:18] Usuario: 3 SolP 455
12:06:56 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:06:56 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:56 AM:DEBUG [usuario_dao.py:35] Usuario a actualizar: Usuario: 3 PepeS 442
12:06:56 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:06:56 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:06:56 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:56 AM:INFO [menu_app_usuario.py:33] Usuario actualizado: 1
12:06:59 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:06:59 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:59 AM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
12:06:59 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:06:59 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:06:59 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:06:59 AM:INFO [menu_app_usuario.py:18] Usuario: 1 LopezR 123
12:06:59 AM:INFO [menu_app_usuario.py:18] Usuario: 2 DiegoP 456
12:06:59 AM:INFO [menu_app_usuario.py:18] Usuario: 3 PepeS 442
12:07:05 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:07:05 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:07:05 AM:DEBUG [usuario_dao.py:43] Usuario a eliminar: Usuario: 3 None None
12:07:05 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:07:05 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:07:05 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:07:05 AM:INFO [menu_app_usuario.py:39] Usuario eliminado satisfactoriamente: 1
12:07:06 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
12:07:06 AM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:07:06 AM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
12:07:06 AM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
12:07:06 AM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
12:07:06 AM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000001EB68C00370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:07:06 AM:INFO [menu_app_usuario.py:18] Usuario: 1 LopezR 123
12:07:06 AM:INFO [menu_app_usuario.py:18] Usuario: 2 DiegoP 456
12:07:11 AM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
05:10:41 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000018C9AC36A50>
05:10:41 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000018C9CC68480; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:10:59 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
05:10:59 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000028876063E00>
05:10:59 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:10:59 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
05:10:59 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
05:10:59 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
05:10:59 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:19 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
05:11:19 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:19 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None rojoL 234
05:11:19 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
05:11:19 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
05:11:19 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:19 PM:INFO [menu_app_usuario.py:25] Usuario insertado: 1
05:11:25 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
05:11:25 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:25 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
05:11:25 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
05:11:25 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
05:11:25 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:25 PM:INFO [menu_app_usuario.py:18] Usuario: 1 rojoL 234
05:11:47 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
05:11:47 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:47 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
05:11:47 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
05:11:47 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
05:11:47 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x0000028875E24370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:11:47 PM:INFO [menu_app_usuario.py:18] Usuario: 1 rojoL 234
05:11:47 PM:INFO [menu_app_usuario.py:18] Usuario: 2 RobertoL 123
05:11:47 PM:INFO [menu_app_usuario.py:18] Usuario: 3 JoseG 443
05:12:25 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
09:14:06 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000020C1B8C6A50>
09:14:06 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x0000020C1D848040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:15:22 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
09:15:22 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002C532B9FCB0>
09:15:22 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002C532920370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:15:22 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
09:15:22 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
09:15:22 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
09:15:22 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002C532920370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:15:22 PM:INFO [menu_app_usuario.py:18] Usuario: 1 LopezR 123
09:15:22 PM:INFO [menu_app_usuario.py:18] Usuario: 2 DiegoP 456
09:17:06 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
09:17:06 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002C532920370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:17:06 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None RicardoR 446
09:17:06 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
09:17:06 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
09:17:06 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002C532920370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:17:06 PM:INFO [menu_app_usuario.py:25] Usuario insertado: 1
09:17:32 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
09:17:32 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002C532920370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:17:32 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None LucianaF 665
09:17:32 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
09:17:32 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
09:17:32 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002C532920370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:17:32 PM:INFO [menu_app_usuario.py:25] Usuario insertado: 1
09:28:14 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
09:31:32 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002CD42256A50>
09:31:32 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002CD44228040; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:38:41 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
09:38:41 PM:DEBUG [conexion.py:39] Creación del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002BCE0A33E00>
09:38:41 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002BCE07F4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:38:41 PM:DEBUG [usuario_dao.py:15] Seleccionando usuarios
09:38:41 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
09:38:41 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
09:38:41 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002BCE07F4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:38:41 PM:INFO [menu_app_usuario.py:18] Usuario: 1 rojoL 234
09:38:41 PM:INFO [menu_app_usuario.py:18] Usuario: 2 RobertoL 123
09:38:41 PM:INFO [menu_app_usuario.py:18] Usuario: 3 JoseG 443
09:39:29 PM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
09:39:29 PM:DEBUG [conexion.py:18] Conexión obtenida del pool: <connection object at 0x000002BCE07F4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:39:29 PM:DEBUG [usuario_dao.py:27] Usuario a insertar: Usuario: None ArielB 554
09:39:29 PM:DEBUG [cursor_del_pool.py:17] Se ejecuta el método exit
09:39:29 PM:DEBUG [cursor_del_pool.py:23] Commit de la transacción
09:39:29 PM:DEBUG [conexion.py:50] Regresamos la conexión al pool: <connection object at 0x000002BCE07F4370; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
09:39:29 PM:INFO [menu_app_usuario.py:25] Usuario insertado: 1
09:39:48 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
09:39:53 PM:INFO [menu_app_usuario.py:42] Has salido de la aplicación, ¡Hasta luego!
